- name: Downloading Grok Exporter  
  ansible.builtin.unarchive:
    src: https://github.com/fstab/grok_exporter/releases/download/v0.2.8/grok_exporter-0.2.8.linux-amd64.zip
    dest: /opt
    remote_src: yes
    owner: "{{app_user}}" 
    group: "{{app_user}}" 

- name: Copying Grok Config file 
  ansible.builtin.template:
    src: config.yml
    dest: /opt/grok_exporter-0.2.8.linux-amd64/config.yml

- name: Copying Grok Systemd file 
  ansible.builtin.file:
    src: grok-exporter.service
    dest: /etc/systemd/system/grok-exporter.service

- name: Restarting Grok-exporter serivce 
  ansible.builtin.systemd_service:
    name: grok-exporter
    state: restarted
    enabled: true
    daemon_reload: true