- name: Configuring hostname 
  ansible.builtin.shell: set-hostname "{{COMPONENT}}-{{ENV}}" 

- name: Configuring Node Exporter
  ansible.builtin.include_role:      # Through this we can all a specific task from a role
    name: prometheus                     # Name of the role to be called 
    tasks_from: node-exporter             # Name of the task in the above mentioned role 
  